#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import sys
import time
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from soc_decomp.nmc_vcorr_it_train_dst_selector_run import TrainDSTSelectorConfig, run


PROFILE_SET = ("VALIDATION", "DST", "FUDS", "US06")


@dataclass(frozen=True)
class Candidate:
    name: str
    model_kind: str
    feature_set: str
    recurrent: str = "gru"
    head_kind: str = "linear"
    train_sampler: str = "temperature_profile_regime_balanced"
    r0_mode: str = "train_temperature"
    r0_profile_quantile: float = 0.5
    temp_mode: str = "none"
    train_temperatures: tuple[float, ...] = (0.0, 25.0, 45.0)
    sequence_training: bool = False
    hidden_size: int = 128
    layers: int = 1
    dropout: float = 0.06
    weight_decay: float = 2e-4
    weight_0: float = 4.0
    weight_25: float = 2.2
    lambda_regime_cvar: float = 0.0
    regime_cvar_top_frac: float = 0.34
    lambda_cold_socbin_cvar: float = 0.0
    cold_socbin_cvar_top_frac: float = 0.34
    cold_socbin_cvar_bin_width: float = 0.1
    cold_socbin_cvar_temp: float = 0.0
    lambda_cold_socbin_bias: float = 0.0
    cold_socbin_bias_bin_width: float = 0.1
    cold_socbin_bias_soc_upper: float = 0.5
    cold_socbin_bias_temp: float = 0.0
    lambda_cold_profile_socbin_underbias: float = 0.0
    cold_profile_socbin_underbias_bin_width: float = 0.1
    cold_profile_socbin_underbias_soc_upper: float = 0.5
    cold_profile_socbin_underbias_temp: float = 0.0
    weight_ema_decay: float = 0.0
    weight_ema_start_epoch: int = 1
    lambda_rex: float = 2.0
    lambda_condinv: float = 0.02
    lambda_profile_adv: float = 0.0
    profile_adv_grl: float = 1.0
    lambda_profile_supcon: float = 0.0
    supcon_temperature: float = 0.15
    lr: float = 8e-4
    lambda_cold_lowsoc_underpred_loss: float = 0.0
    cold_lowsoc_underpred_soc_upper: float = 0.2
    cold_lowsoc_underpred_temp: float = 0.0
    lambda_cold_lowsoc_overpred_loss: float = 0.0
    cold_lowsoc_overpred_soc_upper: float = 0.2
    cold_lowsoc_overpred_temp: float = 0.0
    lambda_regime_asym_loss: float = 0.0
    regime_asym_soc_upper: float = 0.5
    regime_asym_cold_temp: float = 0.0
    regime_asym_under_weight: float = 1.0
    regime_asym_over_weight: float = 1.0
    lambda_lowdyn_highspan_under_loss: float = 0.0
    lowdyn_highspan_soc_upper: float = 0.5
    lowdyn_highspan_cold_temp: float = 0.0
    lowdyn_highspan_dynamic_center: float = 1.4
    lowdyn_highspan_dynamic_sharpness: float = 3.0
    lowdyn_highspan_span_center: float = 0.08
    lowdyn_highspan_span_sharpness: float = 60.0
    voltage_sag_augment_prob: float = 0.0
    voltage_sag_augment_scale: float = 0.0
    voltage_sag_augment_soc_upper: float = 0.5
    voltage_sag_augment_temp: float = 0.0
    hard_region_loss_weight: float = 0.0
    hard_region_soc_threshold: float = 0.4
    hard_region_soc_lower: float = -1.0
    hard_region_soc_upper: float = -1.0
    hard_region_dynamic_weight: float = 0.5
    hard_region_cold_only: bool = False
    cold_corrector_limit: float = 0.08
    cold_corrector_soc_threshold: float = 0.35
    cold_corrector_temp_threshold: float = -0.45
    cold_corrector_gate_sharpness: float = 8.0
    cold_corrector_sag_gate: bool = False
    anchor_residual_limit: float = 0.12
    anchor_residual_limit_init: str = "value"
    anchor_residual_limit_mode: str = "fixed"
    anchor_residual_limit_lower: float = 0.0
    anchor_residual_limit_upper: float = 0.2
    lambda_anchor_loss: float = 0.2


CANDIDATES = (
    Candidate(
        "all_ema_h128_endpoint_mlpcontrol_w1p2",
        "endpoint_mlp",
        "paper_g4_all_ema",
        hidden_size=128,
        weight_0=1.2,
    ),
    Candidate(
        "all_ema_h128_window_mlpcontrol_w1p2",
        "window_summary_mlp",
        "paper_g4_all_ema",
        hidden_size=128,
        weight_0=1.2,
    ),
    Candidate(
        "all_ema_h128_window_mlpcontrol_w1p2_under0p5_lam1p0",
        "window_summary_mlp",
        "paper_g4_all_ema",
        hidden_size=128,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate("all_ema_h128_endpoint_mlp_w0p8", "single", "paper_g4_all_ema", head_kind="mlp", weight_0=0.8),
    Candidate("all_ema_h128_endpoint_gatedmlp_w0p8", "single", "paper_g4_all_ema", head_kind="gated_mlp", weight_0=0.8),
    Candidate("all_ema_h128_endpoint_gatedmlp_w1p2", "single", "paper_g4_all_ema", head_kind="gated_mlp", weight_0=1.2),
    Candidate("all_ema_h128_endpoint_gatedmlp_w2p0", "single", "paper_g4_all_ema", head_kind="gated_mlp", weight_0=2.0),
    Candidate("all_ema_h128_endpoint_gatedmlp_w4p0", "single", "paper_g4_all_ema", head_kind="gated_mlp", weight_0=4.0),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w4p0_under0p4_lam0p25",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=4.0,
        lambda_cold_lowsoc_underpred_loss=0.25,
        cold_lowsoc_underpred_soc_upper=0.4,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w4p0_under0p4_lam0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=4.0,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.4,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w4p0_under0p4_lam1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=4.0,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.4,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p4_lam0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.4,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "coldonly_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        train_temperatures=(0.0,),
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p2_lam1p0_hard0p5_soc0p3_0p4",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.2,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.3,
        hard_region_soc_upper=0.4,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p2_lam2p5_hard0p5_soc0p3_0p4",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.2,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.3,
        hard_region_soc_upper=0.4,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p2_lam0p5_hard0p5_soc0p3_0p4",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.2,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.3,
        hard_region_soc_upper=0.4,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p2_lam2p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.2,
    ),
    Candidate(
        "transmin_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5",
        "single",
        "paper_g4_all_ema_transient_min",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5_coldscvar0p10",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_socbin_cvar=0.10,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5_coldscvar0p25",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_socbin_cvar=0.25,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5_coldscvar0p50",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_socbin_cvar=0.50,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5_vsag0p05",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        voltage_sag_augment_prob=0.5,
        voltage_sag_augment_scale=0.05,
        voltage_sag_augment_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5_vsag0p10",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        voltage_sag_augment_prob=0.5,
        voltage_sag_augment_scale=0.10,
        voltage_sag_augment_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_lstm_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5",
        "single",
        "paper_g4_all_ema",
        recurrent="lstm",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_rnn_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5",
        "single",
        "paper_g4_all_ema",
        recurrent="rnn",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_transformer_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5",
        "single",
        "paper_g4_all_ema",
        recurrent="transformer",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p25",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.25,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam2p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam2p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_regime_h128_endpoint_gatedmlp_w1p2_under0p5_lam2p5",
        "single",
        "paper_g4_all_ema_regime",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam3p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam3p0_vsag0p05",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        voltage_sag_augment_prob=0.5,
        voltage_sag_augment_scale=0.05,
        voltage_sag_augment_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam3p0_vsag0p10",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        voltage_sag_augment_prob=0.5,
        voltage_sag_augment_scale=0.10,
        voltage_sag_augment_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_vsag1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        voltage_sag_augment_prob=0.5,
        voltage_sag_augment_scale=1.0,
        voltage_sag_augment_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_vsag2p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        voltage_sag_augment_prob=0.5,
        voltage_sag_augment_scale=2.0,
        voltage_sag_augment_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_regime_h128_endpoint_gatedmlp_w1p2_under0p5_lam3p0",
        "single",
        "paper_g4_all_ema_regime",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam3p0_drop0p10",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        dropout=0.10,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam3p0_wd1e3",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_decay=1e-3,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h64_endpoint_gatedmlp_w1p2_under0p5_lam3p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        hidden_size=64,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam3p0_ldhs1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_lowdyn_highspan_under_loss=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam3p0_ldhs2p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_lowdyn_highspan_under_loss=2.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam4p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=4.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam5p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=5.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_sequence_gatedmlp_w1p2_under0p5_lam2p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        sequence_training=True,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_sequence_gatedmlp_w1p2_under0p5_lam3p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        sequence_training=True,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=3.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_bias0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_cold_socbin_bias=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_bias1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_cold_socbin_bias=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_bias2p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_cold_socbin_bias=2.0,
    ),
    Candidate(
        "coldonly_all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        train_temperatures=(0.0,),
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "tempbias_all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        temp_mode="bias",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "tempaff_all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        temp_mode="hard_affine",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "tempmoe_all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        temp_mode="moe",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "temphardheads_all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        temp_mode="hard_heads",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "socbal_all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        train_sampler="temperature_profile_soc_balanced",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "transmin_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema_transient_min",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "shape_norm_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_rex1p0",
        "single",
        "paper_g4_all_ema_shape_norm",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_rex=1.0,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_rex=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_rex0p8",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_rex=0.8,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_wema0p99",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        weight_ema_decay=0.99,
        weight_ema_start_epoch=100,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_wema0p995",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        weight_ema_decay=0.995,
        weight_ema_start_epoch=100,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_lr4e4",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lr=4e-4,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_lr2e4",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lr=2e-4,
    ),
    Candidate(
        "all_ema_h192_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        hidden_size=192,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h256_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        hidden_size=256,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p5_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.5,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over1p0_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=1.0,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_cvar0p1",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_regime_cvar=0.1,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5_cvar0p3",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_regime_cvar=0.3,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam2p5_cvar0p1",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_regime_cvar=0.1,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_regasym0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_regime_asym_loss=0.5,
        regime_asym_soc_upper=0.5,
        regime_asym_under_weight=1.0,
        regime_asym_over_weight=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_regasym1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_regime_asym_loss=1.0,
        regime_asym_soc_upper=0.5,
        regime_asym_under_weight=1.0,
        regime_asym_over_weight=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_regasym1p0_u2o1",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_regime_asym_loss=1.0,
        regime_asym_soc_upper=0.5,
        regime_asym_under_weight=2.0,
        regime_asym_over_weight=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_ldhs0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_lowdyn_highspan_under_loss=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_ldhs1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_lowdyn_highspan_under_loss=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_ldhs2p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_lowdyn_highspan_under_loss=2.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_lowdyn1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_lowdyn_highspan_under_loss=1.0,
        lowdyn_highspan_span_center=-10.0,
        lowdyn_highspan_span_sharpness=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_lowdyn2p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        lambda_lowdyn_highspan_under_loss=2.0,
        lowdyn_highspan_span_center=-10.0,
        lowdyn_highspan_span_sharpness=1.0,
    ),
    Candidate(
        "signedcorr_gated_w1p2_under2p5_over0p25_soc0p5_corr0p08",
        "normal_cold_low_soc_signed_sequence",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        cold_corrector_limit=0.08,
        cold_corrector_soc_threshold=0.5,
    ),
    Candidate(
        "positivecorr_gated_w1p2_under2p5_soc0p5_corr0p08",
        "normal_cold_low_soc_positive_sequence",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        cold_corrector_limit=0.08,
        cold_corrector_soc_threshold=0.5,
    ),
    Candidate(
        "positivecorr_gated_w1p2_under2p5_soc0p5_corr0p12",
        "normal_cold_low_soc_positive_sequence",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        cold_corrector_limit=0.12,
        cold_corrector_soc_threshold=0.5,
    ),
    Candidate(
        "signedcorr_gated_w1p2_under2p5_over0p25_soc0p5_corr0p12",
        "normal_cold_low_soc_signed_sequence",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
        cold_corrector_limit=0.12,
        cold_corrector_soc_threshold=0.5,
    ),
    Candidate(
        "coldregbias_gated_w1p4_under0p5_lam1p0_corr0p012",
        "cold_regime_signed_bias_sequence",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.4,
        weight_25=2.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        cold_corrector_limit=0.012,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w0p8_under0p5_lam1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=0.8,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam2p0_hard0p5_cold0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam2p0_hard1p0_cold0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=1.0,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p25_cold0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.25,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p75_cold0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.75,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p75_hard0p25_cold0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.75,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.25,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p75_hard0p5_cold0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.75,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_dyn0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.0,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5_hard0p25_cold0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.25,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5_hard0p5_cold0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p4_lam1p0_hard0p25_cold0p4",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.4,
        hard_region_loss_weight=0.25,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.4,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "profub0p5_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
        lambda_cold_profile_socbin_underbias=0.5,
    ),
    Candidate(
        "profub1p0_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
        lambda_cold_profile_socbin_underbias=1.0,
    ),
    Candidate(
        "profub2p0_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
        lambda_cold_profile_socbin_underbias=2.0,
    ),
    Candidate(
        "coldonly_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        train_temperatures=(0.0,),
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "tempbias_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        temp_mode="bias",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "tempaff_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        temp_mode="hard_affine",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "socbal_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        train_sampler="temperature_profile_soc_balanced",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "socregbal_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        train_sampler="temperature_profile_soc_regime_balanced",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "profadv1e3_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
        lambda_profile_adv=0.001,
    ),
    Candidate(
        "full23_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g6_full23",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "relaxupper_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_relax_upper",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "profiler0_all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        r0_mode="profile_observed",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "profiler0_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        r0_mode="profile_observed",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "trainr0p80_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        r0_mode="train_temperature_quantile",
        r0_profile_quantile=0.8,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "trainr0p90_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        r0_mode="train_temperature_quantile",
        r0_profile_quantile=0.9,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "trainr0p80_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam2p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        r0_mode="train_temperature_quantile",
        r0_profile_quantile=0.8,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "trainr0p90_all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam2p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        r0_mode="train_temperature_quantile",
        r0_profile_quantile=0.9,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
    ),
    Candidate(
        "profiler0p80_all_ema_h128_endpoint_gatedmlp_w1p2_under2p5_over0p25_soc0p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        r0_mode="profile_observed",
        r0_profile_quantile=0.8,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=2.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_cold_lowsoc_overpred_loss=0.25,
        cold_lowsoc_overpred_soc_upper=0.5,
    ),
    Candidate(
        "transmin_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema_transient_min",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0_wema0p99",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
        weight_ema_decay=0.99,
        weight_ema_start_epoch=100,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0_wema0p995",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
        weight_ema_decay=0.995,
        weight_ema_start_epoch=100,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex0p8",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=0.8,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p2",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.2,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p5",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.5,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0_lr6e4",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
        lr=6e-4,
    ),
    Candidate(
        "all_ema_h96_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        hidden_size=96,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "all_ema_h160_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        hidden_size=160,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "all_ema_h192_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        hidden_size=192,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "all_ema_h96_l2_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        hidden_size=96,
        layers=2,
        dropout=0.07,
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5_rex1p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        lambda_rex=1.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_rex0p0",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_rex=0.0,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_coldscvar0p10",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_cold_socbin_cvar=0.10,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam1p0_hard0p5_cold0p5_coldscvar0p25",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=1.0,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.5,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.5,
        hard_region_cold_only=True,
        lambda_cold_socbin_cvar=0.25,
    ),
    Candidate(
        "all_ema_h128_endpoint_gatedmlp_w1p2_under0p5_lam0p5_hard0p25_cold0p5_dyn0_coldscvar0p10",
        "single",
        "paper_g4_all_ema",
        head_kind="gated_mlp",
        weight_0=1.2,
        lambda_cold_lowsoc_underpred_loss=0.5,
        cold_lowsoc_underpred_soc_upper=0.5,
        hard_region_loss_weight=0.25,
        hard_region_soc_lower=0.0,
        hard_region_soc_upper=0.5,
        hard_region_dynamic_weight=0.0,
        hard_region_cold_only=True,
        lambda_cold_socbin_cvar=0.10,
    ),
    Candidate("all_ema_start_h128_endpoint_gatedmlp_w0p8", "single", "paper_g4_all_ema_start", head_kind="gated_mlp", weight_0=0.8),
    Candidate("all_ema_start_h128_endpoint_gatedmlp_w1p2", "single", "paper_g4_all_ema_start", head_kind="gated_mlp", weight_0=1.2),
    Candidate(
        "all_ema_h128_endpoint_resmlp0p5_w0p8",
        "single",
        "paper_g4_all_ema",
        head_kind="residual_mlp_0p5",
        weight_0=0.8,
    ),
    Candidate(
        "all_ema_h128_endpoint_resmlp1p0_w0p8",
        "single",
        "paper_g4_all_ema",
        head_kind="residual_mlp_1p0",
        weight_0=0.8,
    ),
    Candidate("all_ema_h128_endpoint_w0p8_lr8e4", "single", "paper_g4_all_ema", weight_0=0.8),
    Candidate("all_ema_h128_endpoint_w0p8_lr4e4", "single", "paper_g4_all_ema", weight_0=0.8, lr=4e-4),
    Candidate("all_ema_h128_endpoint_w0p8_lr2e4", "single", "paper_g4_all_ema", weight_0=0.8, lr=2e-4),
    Candidate("all_ema_h128_endpoint_w1p2_lr4e4", "single", "paper_g4_all_ema", weight_0=1.2, lr=4e-4),
    Candidate("all_ema_start_endpoint_w0p8", "single", "paper_g4_all_ema_start", weight_0=0.8),
    Candidate("all_ema_start_endpoint_w4", "single", "paper_g4_all_ema_start"),
    Candidate("eqdyn_start_endpoint_w0p8", "single", "paper_g4_eqdyn_start", weight_0=0.8),
    Candidate("eqdyn_start_endpoint_w4", "single", "paper_g4_eqdyn_start"),
    Candidate(
        "eqdyn_start_h64_l2_seq_cvar_wd2e3_w0p8_w25p15",
        "single",
        "paper_g4_eqdyn_start",
        sequence_training=True,
        hidden_size=64,
        layers=2,
        dropout=0.07,
        weight_decay=2e-3,
        weight_0=0.8,
        weight_25=1.5,
        lambda_regime_cvar=0.1,
    ),
    Candidate("eqdyn_endpoint_w4", "single", "paper_g4_eqdyn"),
    Candidate("eqdyn_regime_endpoint_w4", "single", "paper_g4_eqdyn_regime"),
    Candidate("eqdyn_mha_w4", "single_mha_endpoint", "paper_g4_eqdyn"),
    Candidate("eqdyn_multiscale_w4", "single_multiscale_endpoint", "paper_g4_eqdyn"),
    Candidate("eqdyn_ctx_learned_g4global_w4", "single_dual_context_eqdyn_g4global_endpoint", "paper_g4_eqdyn"),
    Candidate("eqdyn_ctx_dynamic_g4global_w4", "single_dual_context_dynamic_gate_eqdyn_g4full_endpoint", "paper_g4_eqdyn"),
    Candidate("eqdyn_ctx_fusion_g4global_w4", "single_dual_context_fusion_eqdyn_g4full_endpoint", "paper_g4_eqdyn"),
    Candidate(
        "eqdyn_regime_ctx_fusion_g4global_w4",
        "single_dual_context_fusion_eqdyn_g4full_endpoint",
        "paper_g4_eqdyn_regime",
    ),
    Candidate(
        "eqdyn_h64_l2_endpoint_cvar_wd2e3_w0p8_w25p15",
        "single",
        "paper_g4_eqdyn",
        sequence_training=False,
        hidden_size=64,
        layers=2,
        dropout=0.07,
        weight_decay=2e-3,
        weight_0=0.8,
        weight_25=1.5,
        lambda_regime_cvar=0.1,
    ),
    Candidate(
        "tbr_interp25_tzgate_dynscale_gru_g4ema_lim012_learn",
        "anchor_residual_tbr_interp25_tzgate_dynscale_sequence",
        "paper_g4_all_ema",
        recurrent="gru",
        head_kind="linear",
        sequence_training=True,
        hidden_size=128,
        layers=1,
        dropout=0.06,
        weight_decay=2e-4,
        weight_0=0.8,
        weight_25=2.2,
        anchor_residual_limit=0.12,
        anchor_residual_limit_init="rand01",
        anchor_residual_limit_mode="learnable",
        anchor_residual_limit_lower=0.0,
        anchor_residual_limit_upper=0.2,
        lambda_anchor_loss=0.1,
    ),
    Candidate(
        "tbr_interp25_tzgate_dynscale_gru_g4ema_lim004_fixed",
        "anchor_residual_tbr_interp25_tzgate_dynscale_sequence",
        "paper_g4_all_ema",
        recurrent="gru",
        head_kind="linear",
        sequence_training=True,
        hidden_size=128,
        layers=1,
        dropout=0.06,
        weight_decay=2e-4,
        weight_0=0.8,
        weight_25=2.2,
        anchor_residual_limit=0.04,
        anchor_residual_limit_init="value",
        anchor_residual_limit_mode="fixed",
        anchor_residual_limit_lower=0.0,
        anchor_residual_limit_upper=0.08,
        lambda_anchor_loss=0.1,
    ),
)


def parse_csv(raw: str) -> tuple[str, ...]:
    return tuple(x.strip() for x in str(raw).split(",") if x.strip())


def parse_seeds(raw: str) -> tuple[int, ...]:
    return tuple(int(x.strip()) for x in str(raw).split(",") if x.strip())


def train_profiles_for_holdout(holdout: str) -> tuple[str, ...]:
    holdout = holdout.upper()
    return tuple(profile for profile in PROFILE_SET if profile != holdout)


def format_eta(seconds: float) -> str:
    seconds = max(0, int(seconds))
    hours, rem = divmod(seconds, 3600)
    minutes, sec = divmod(rem, 60)
    return f"{hours:02d}:{minutes:02d}:{sec:02d}"


def seed_tag(seeds: tuple[int, ...]) -> str:
    return "seeds" + "".join(str(seed) for seed in seeds)


def candidate_map() -> dict[str, Candidate]:
    return {candidate.name: candidate for candidate in CANDIDATES}


def prefix_for(candidate: Candidate, holdout: str, seeds: tuple[int, ...], epochs: int, batch_size: int, tag: str) -> str:
    candidate_tag = candidate.name
    if len(candidate_tag) > 72:
        digest = hashlib.sha1(candidate_tag.encode("utf-8")).hexdigest()[:10]
        candidate_tag = f"{candidate_tag[:56]}_{digest}"
    return (
        f"soc80_goal_w50_{tag}_{candidate_tag}_"
        f"holdout{holdout.lower()}_{seed_tag(seeds)}_b{int(batch_size)}_e{int(epochs)}"
    )


def cfg_for_job(candidate: Candidate, holdout: str, args: argparse.Namespace, prefix: str) -> TrainDSTSelectorConfig:
    epochs = int(args.epochs)
    return TrainDSTSelectorConfig(
        base_dir=Path(args.base_dir),
        raw_root=Path(args.raw_root),
        output_prefix=prefix,
        seeds=parse_seeds(args.seeds),
        train_profiles=train_profiles_for_holdout(holdout),
        valid_profiles=("NONE",),
        test_profiles=(holdout.upper(),),
        train_temperatures=tuple(float(x) for x in candidate.train_temperatures),
        valid_temperatures=(),
        test_temperatures=(0.0, 25.0, 45.0),
        window_len=50,
        stride=3,
        epochs=epochs,
        stage1_eval_every=epochs,
        selector_min_epoch=epochs,
        selector_max_epoch=0,
        fixed_stage1_epoch=epochs,
        batch_size=int(args.batch_size),
        num_workers=0,
        prefetch_factor=2,
        lr=float(candidate.lr),
        weight_decay=float(candidate.weight_decay),
        hidden_size=int(candidate.hidden_size),
        layers=int(candidate.layers),
        kernel_size=5,
        model_kind=str(candidate.model_kind),
        recurrent=str(candidate.recurrent),
        head_kind=str(candidate.head_kind),
        dropout=float(candidate.dropout),
        feature_set=str(candidate.feature_set),
        stage2_feature_set=str(candidate.feature_set),
        temp_mode=str(candidate.temp_mode),
        train_sampler=str(candidate.train_sampler),
        r0_mode=str(candidate.r0_mode),
        r0_profile_quantile=float(candidate.r0_profile_quantile),
        stage1_selector="last_epoch",
        selector_regime_min_windows=30,
        lambda_regime_cvar=float(candidate.lambda_regime_cvar),
        regime_cvar_top_frac=float(candidate.regime_cvar_top_frac),
        lambda_cold_socbin_cvar=float(candidate.lambda_cold_socbin_cvar),
        cold_socbin_cvar_top_frac=float(candidate.cold_socbin_cvar_top_frac),
        cold_socbin_cvar_bin_width=float(candidate.cold_socbin_cvar_bin_width),
        cold_socbin_cvar_temp=float(candidate.cold_socbin_cvar_temp),
        lambda_cold_socbin_bias=float(candidate.lambda_cold_socbin_bias),
        cold_socbin_bias_bin_width=float(candidate.cold_socbin_bias_bin_width),
        cold_socbin_bias_soc_upper=float(candidate.cold_socbin_bias_soc_upper),
        cold_socbin_bias_temp=float(candidate.cold_socbin_bias_temp),
        lambda_cold_profile_socbin_underbias=float(candidate.lambda_cold_profile_socbin_underbias),
        cold_profile_socbin_underbias_bin_width=float(candidate.cold_profile_socbin_underbias_bin_width),
        cold_profile_socbin_underbias_soc_upper=float(candidate.cold_profile_socbin_underbias_soc_upper),
        cold_profile_socbin_underbias_temp=float(candidate.cold_profile_socbin_underbias_temp),
        weight_ema_decay=float(candidate.weight_ema_decay),
        weight_ema_start_epoch=int(candidate.weight_ema_start_epoch),
        lambda_profile_adv=float(candidate.lambda_profile_adv),
        profile_adv_grl=float(candidate.profile_adv_grl),
        lambda_profile_supcon=float(candidate.lambda_profile_supcon),
        supcon_temperature=float(candidate.supcon_temperature),
        lambda_zbin_cvar=0.0,
        zbin_cvar_top_frac=0.34,
        lambda_condinv=float(candidate.lambda_condinv),
        lambda_rex=float(candidate.lambda_rex),
        weight_0=float(candidate.weight_0),
        weight_25=float(candidate.weight_25),
        weight_45=1.0,
        lambda_cold_lowsoc_underpred_loss=float(candidate.lambda_cold_lowsoc_underpred_loss),
        cold_lowsoc_underpred_soc_upper=float(candidate.cold_lowsoc_underpred_soc_upper),
        cold_lowsoc_underpred_temp=float(candidate.cold_lowsoc_underpred_temp),
        lambda_cold_lowsoc_overpred_loss=float(candidate.lambda_cold_lowsoc_overpred_loss),
        cold_lowsoc_overpred_soc_upper=float(candidate.cold_lowsoc_overpred_soc_upper),
        cold_lowsoc_overpred_temp=float(candidate.cold_lowsoc_overpred_temp),
        lambda_regime_asym_loss=float(candidate.lambda_regime_asym_loss),
        regime_asym_soc_upper=float(candidate.regime_asym_soc_upper),
        regime_asym_cold_temp=float(candidate.regime_asym_cold_temp),
        regime_asym_under_weight=float(candidate.regime_asym_under_weight),
        regime_asym_over_weight=float(candidate.regime_asym_over_weight),
        lambda_lowdyn_highspan_under_loss=float(candidate.lambda_lowdyn_highspan_under_loss),
        lowdyn_highspan_soc_upper=float(candidate.lowdyn_highspan_soc_upper),
        lowdyn_highspan_cold_temp=float(candidate.lowdyn_highspan_cold_temp),
        lowdyn_highspan_dynamic_center=float(candidate.lowdyn_highspan_dynamic_center),
        lowdyn_highspan_dynamic_sharpness=float(candidate.lowdyn_highspan_dynamic_sharpness),
        lowdyn_highspan_span_center=float(candidate.lowdyn_highspan_span_center),
        lowdyn_highspan_span_sharpness=float(candidate.lowdyn_highspan_span_sharpness),
        voltage_sag_augment_prob=float(candidate.voltage_sag_augment_prob),
        voltage_sag_augment_scale=float(candidate.voltage_sag_augment_scale),
        voltage_sag_augment_soc_upper=float(candidate.voltage_sag_augment_soc_upper),
        voltage_sag_augment_temp=float(candidate.voltage_sag_augment_temp),
        hard_region_loss_weight=float(candidate.hard_region_loss_weight),
        hard_region_soc_threshold=float(candidate.hard_region_soc_threshold),
        hard_region_soc_lower=float(candidate.hard_region_soc_lower),
        hard_region_soc_upper=float(candidate.hard_region_soc_upper),
        hard_region_dynamic_weight=float(candidate.hard_region_dynamic_weight),
        hard_region_cold_only=bool(candidate.hard_region_cold_only),
        cold_corrector_limit=float(candidate.cold_corrector_limit),
        cold_corrector_soc_threshold=float(candidate.cold_corrector_soc_threshold),
        cold_corrector_temp_threshold=float(candidate.cold_corrector_temp_threshold),
        cold_corrector_gate_sharpness=float(candidate.cold_corrector_gate_sharpness),
        cold_corrector_sag_gate=bool(candidate.cold_corrector_sag_gate),
        anchor_residual_limit=float(candidate.anchor_residual_limit),
        anchor_residual_limit_init=str(candidate.anchor_residual_limit_init),
        anchor_residual_limit_mode=str(candidate.anchor_residual_limit_mode),
        anchor_residual_limit_lower=float(candidate.anchor_residual_limit_lower),
        anchor_residual_limit_upper=float(candidate.anchor_residual_limit_upper),
        lambda_anchor_loss=float(candidate.lambda_anchor_loss),
        stage2_select_rule="none",
        skip_stage2=True,
        save_predictions=True,
        save_final_weights=True,
        final_only_eval=True,
        skip_train_final_eval=True,
        valid_split_mode="profile",
        sequence_training=bool(candidate.sequence_training),
        cache_dataset_cuda=True,
    )


def read_summary(path: Path, candidate: Candidate, holdout: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    selected = df[df["variant"].astype(str).str.contains("selected", case=False, na=False)]
    if len(selected):
        df = selected
    rows = []
    for _, row in df.drop_duplicates(subset=["seed", "0.0", "25.0", "45.0"]).iterrows():
        rows.append(
            {
                "candidate": candidate.name,
                "model_kind": candidate.model_kind,
                "feature_set": candidate.feature_set,
                "holdout": holdout.upper(),
                "seed": int(row["seed"]),
                "window_len": 50,
                "recurrent": candidate.recurrent,
                "head_kind": candidate.head_kind,
                "train_sampler": candidate.train_sampler,
                "r0_mode": candidate.r0_mode,
                "r0_profile_quantile": float(candidate.r0_profile_quantile),
                "temp_mode": candidate.temp_mode,
                "train_temperatures": ";".join(str(float(x)) for x in candidate.train_temperatures),
                "sequence_training": bool(candidate.sequence_training),
                "hidden_size": int(candidate.hidden_size),
                "layers": int(candidate.layers),
                "dropout": float(candidate.dropout),
                "weight_decay": float(candidate.weight_decay),
                "lambda_rex": float(candidate.lambda_rex),
                "lambda_condinv": float(candidate.lambda_condinv),
                "lambda_profile_adv": float(candidate.lambda_profile_adv),
                "profile_adv_grl": float(candidate.profile_adv_grl),
                "lambda_profile_supcon": float(candidate.lambda_profile_supcon),
                "supcon_temperature": float(candidate.supcon_temperature),
                "lambda_regime_cvar": float(candidate.lambda_regime_cvar),
                "lambda_cold_socbin_cvar": float(candidate.lambda_cold_socbin_cvar),
                "cold_socbin_cvar_top_frac": float(candidate.cold_socbin_cvar_top_frac),
                "cold_socbin_cvar_bin_width": float(candidate.cold_socbin_cvar_bin_width),
                "cold_socbin_cvar_temp": float(candidate.cold_socbin_cvar_temp),
                "lambda_cold_socbin_bias": float(candidate.lambda_cold_socbin_bias),
                "cold_socbin_bias_bin_width": float(candidate.cold_socbin_bias_bin_width),
                "cold_socbin_bias_soc_upper": float(candidate.cold_socbin_bias_soc_upper),
                "cold_socbin_bias_temp": float(candidate.cold_socbin_bias_temp),
                "lambda_cold_profile_socbin_underbias": float(candidate.lambda_cold_profile_socbin_underbias),
                "cold_profile_socbin_underbias_bin_width": float(candidate.cold_profile_socbin_underbias_bin_width),
                "cold_profile_socbin_underbias_soc_upper": float(candidate.cold_profile_socbin_underbias_soc_upper),
                "cold_profile_socbin_underbias_temp": float(candidate.cold_profile_socbin_underbias_temp),
                "weight_ema_decay": float(candidate.weight_ema_decay),
                "weight_ema_start_epoch": int(candidate.weight_ema_start_epoch),
                "weight_0": float(candidate.weight_0),
                "weight_25": float(candidate.weight_25),
                "lambda_cold_lowsoc_underpred_loss": float(candidate.lambda_cold_lowsoc_underpred_loss),
                "cold_lowsoc_underpred_soc_upper": float(candidate.cold_lowsoc_underpred_soc_upper),
                "lambda_cold_lowsoc_overpred_loss": float(candidate.lambda_cold_lowsoc_overpred_loss),
                "cold_lowsoc_overpred_soc_upper": float(candidate.cold_lowsoc_overpred_soc_upper),
                "lambda_regime_asym_loss": float(candidate.lambda_regime_asym_loss),
                "regime_asym_under_weight": float(candidate.regime_asym_under_weight),
                "regime_asym_over_weight": float(candidate.regime_asym_over_weight),
                "lambda_lowdyn_highspan_under_loss": float(candidate.lambda_lowdyn_highspan_under_loss),
                "lowdyn_highspan_dynamic_center": float(candidate.lowdyn_highspan_dynamic_center),
                "lowdyn_highspan_span_center": float(candidate.lowdyn_highspan_span_center),
                "voltage_sag_augment_prob": float(candidate.voltage_sag_augment_prob),
                "voltage_sag_augment_scale": float(candidate.voltage_sag_augment_scale),
                "voltage_sag_augment_soc_upper": float(candidate.voltage_sag_augment_soc_upper),
                "hard_region_loss_weight": float(candidate.hard_region_loss_weight),
                "hard_region_soc_lower": float(candidate.hard_region_soc_lower),
                "hard_region_soc_upper": float(candidate.hard_region_soc_upper),
                "hard_region_dynamic_weight": float(candidate.hard_region_dynamic_weight),
                "hard_region_cold_only": bool(candidate.hard_region_cold_only),
                "cold_corrector_limit": float(candidate.cold_corrector_limit),
                "cold_corrector_soc_threshold": float(candidate.cold_corrector_soc_threshold),
                "anchor_residual_limit": float(candidate.anchor_residual_limit),
                "anchor_residual_limit_init": str(candidate.anchor_residual_limit_init),
                "anchor_residual_limit_mode": str(candidate.anchor_residual_limit_mode),
                "anchor_residual_limit_lower": float(candidate.anchor_residual_limit_lower),
                "anchor_residual_limit_upper": float(candidate.anchor_residual_limit_upper),
                "lambda_anchor_loss": float(candidate.lambda_anchor_loss),
                "mae_0C": float(row["0.0"]),
                "mae_25C": float(row["25.0"]),
                "mae_45C": float(row["45.0"]),
                "source": path.name,
            }
        )
    return pd.DataFrame(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-dir", default=str(PROJECT_ROOT))
    parser.add_argument("--raw-root", default="nmc_soc80_train_nofloor_qmax")
    parser.add_argument("--holdouts", default="VALIDATION")
    parser.add_argument("--seeds", default="0")
    parser.add_argument("--epochs", type=int, default=220)
    parser.add_argument("--batch-size", type=int, default=2048)
    parser.add_argument("--tag", default="context_screen_v1")
    parser.add_argument("--candidates", default="all")
    parser.add_argument("--skip-existing", action="store_true")
    args = parser.parse_args()

    out_dir = Path(args.base_dir) / "nmc_goal_vcorr_it_train_dst_selector_results"
    out_dir.mkdir(parents=True, exist_ok=True)
    cmap = candidate_map()
    selected_names = tuple(cmap) if str(args.candidates).lower() == "all" else parse_csv(args.candidates)
    missing = [name for name in selected_names if name not in cmap]
    if missing:
        raise SystemExit(f"unknown candidates: {missing}")

    seeds = parse_seeds(args.seeds)
    jobs = [(cmap[name], holdout.upper()) for holdout in parse_csv(args.holdouts) for name in selected_names]
    started = time.time()
    manifest_rows = []
    for idx, (candidate, holdout) in enumerate(jobs, start=1):
        prefix = prefix_for(candidate, holdout, seeds, int(args.epochs), int(args.batch_size), str(args.tag))
        summary_path = out_dir / f"{prefix}_test_summary.csv"
        if args.skip_existing and summary_path.exists():
            print(f"[skip] {idx}/{len(jobs)} {candidate.name} {holdout} -> {summary_path.name}", flush=True)
        else:
            elapsed = time.time() - started
            per_job = elapsed / max(1, idx - 1) if idx > 1 else 0.0
            eta = per_job * (len(jobs) - idx + 1)
            print(
                f"[run] {idx}/{len(jobs)} {candidate.name} {holdout} "
                f"elapsed={format_eta(elapsed)} eta={format_eta(eta)}",
                flush=True,
            )
            run(cfg_for_job(candidate, holdout, args, prefix))
        manifest_rows.append(
            {
                "candidate": candidate.name,
                "holdout": holdout,
                "summary_path": summary_path.name,
            }
        )

    frames = []
    for row in manifest_rows:
        path = out_dir / row["summary_path"]
        if path.exists():
            frames.append(read_summary(path, cmap[row["candidate"]], row["holdout"]))
    seed_df = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    seed_path = out_dir / f"soc80_goal_w50_{args.tag}_seed_summary.csv"
    seed_df.sort_values(["holdout", "mae_0C", "candidate"]).to_csv(seed_path, index=False)
    if len(seed_df):
        agg = (
            seed_df.groupby(
                [
                    "candidate",
                    "model_kind",
                    "feature_set",
                    "holdout",
                    "window_len",
                    "recurrent",
                    "head_kind",
                    "train_sampler",
                    "r0_mode",
                    "r0_profile_quantile",
                    "temp_mode",
                    "train_temperatures",
                    "sequence_training",
                    "hidden_size",
                    "layers",
                    "dropout",
                    "weight_decay",
                    "lambda_rex",
                    "lambda_condinv",
                    "lambda_profile_adv",
                    "profile_adv_grl",
                    "lambda_profile_supcon",
                    "supcon_temperature",
                    "lambda_regime_cvar",
                    "lambda_cold_socbin_cvar",
                    "cold_socbin_cvar_top_frac",
                    "cold_socbin_cvar_bin_width",
                    "cold_socbin_cvar_temp",
                    "lambda_cold_socbin_bias",
                    "cold_socbin_bias_bin_width",
                    "cold_socbin_bias_soc_upper",
                    "cold_socbin_bias_temp",
                    "lambda_cold_profile_socbin_underbias",
                    "cold_profile_socbin_underbias_bin_width",
                    "cold_profile_socbin_underbias_soc_upper",
                    "cold_profile_socbin_underbias_temp",
                    "weight_ema_decay",
                    "weight_ema_start_epoch",
                    "weight_0",
                    "weight_25",
                    "lambda_cold_lowsoc_underpred_loss",
                    "cold_lowsoc_underpred_soc_upper",
                    "lambda_cold_lowsoc_overpred_loss",
                    "cold_lowsoc_overpred_soc_upper",
                    "lambda_regime_asym_loss",
                    "regime_asym_under_weight",
                    "regime_asym_over_weight",
                    "lambda_lowdyn_highspan_under_loss",
                    "lowdyn_highspan_dynamic_center",
                    "lowdyn_highspan_span_center",
                    "voltage_sag_augment_prob",
                    "voltage_sag_augment_scale",
                    "voltage_sag_augment_soc_upper",
                    "hard_region_loss_weight",
                    "hard_region_soc_lower",
                    "hard_region_soc_upper",
                    "hard_region_dynamic_weight",
                    "hard_region_cold_only",
                    "cold_corrector_limit",
                    "cold_corrector_soc_threshold",
                    "anchor_residual_limit",
                    "anchor_residual_limit_init",
                    "anchor_residual_limit_mode",
                    "anchor_residual_limit_lower",
                    "anchor_residual_limit_upper",
                    "lambda_anchor_loss",
                ],
                as_index=False,
            )
            .agg(
                n_seeds=("seed", "nunique"),
                mae_0C_mean=("mae_0C", "mean"),
                mae_0C_std=("mae_0C", "std"),
                mae_0C_min=("mae_0C", "min"),
                mae_0C_max=("mae_0C", "max"),
                mae_25C_mean=("mae_25C", "mean"),
                mae_45C_mean=("mae_45C", "mean"),
            )
            .sort_values(["holdout", "mae_0C_mean", "mae_0C_max"])
        )
    else:
        agg = pd.DataFrame()
    agg_path = out_dir / f"soc80_goal_w50_{args.tag}_agg_summary.csv"
    agg.to_csv(agg_path, index=False)
    print(f"[done] seed_summary={seed_path}", flush=True)
    print(f"[done] agg_summary={agg_path}", flush=True)


if __name__ == "__main__":
    main()
